### ISSUE TITLE
单词拼写

### ISSUE THREAD

**Issue by DD-L** [jaywcjlove/store.js#1]
这么多 star 了，怎么没 issue。闲来没事，提个

![api](https://cloud.githubusercontent.com/assets/10693555/14780750/fc4a6e74-0b10-11e6-9b99-9933f74f6020.png)

Application Programming Interface

**Comment by jaywcjlove** [comment]
😳  不要调戏哥哥

**Comment by DD-L** [comment]
没有啦，AIP 什么鬼，是不是 API ?

**Comment by jaywcjlove** [comment]
😄   thx!  我以为你调戏我来到
