### ISSUE TITLE
我看源码里面没有定时清除，为什么大概过1分钟就清除了，求教

### ISSUE THREAD

**Issue by nj-novice** [jaywcjlove/store.js#11]

**Comment by jaywcjlove** [comment]
可能分析：

1. 调用了接口清除了，`store(false);`老的API很容易清空，因为传进去对象的可能会是 `false`
2. 浏览器设置了清理？
3. 通过各种安全卫士清理了？

**Comment by nj-novice** [comment]
感谢您的解答，现在好了，是我自己代码问题。。。嘿嘿  
期待在定时清理方面再来个升级啥的，对我这种伸手党简直了  ：）
