### ISSUE TITLE
使用localStorage去读取store存储的数据，会多出双引号

### ISSUE THREAD

**Issue by mrliusu** [jaywcjlove/store.js#12]
store与localStorage的结合问题,使用localStorage去读取store存储的数据，会多出双引号
store.set('city', '深圳')
store.get('city') // 深圳
localStorage.city // “深圳”
localStorage.getItem('city')  // “深圳”

**Comment by jaywcjlove** [comment]
@mrliusu 因为为了直接存储 `JSON` 对象，你可以以下面方式获取

```js
JSON.parse(localStorage.getItem('city'))
```
