### ISSUE TITLE
isJSON方法

### ISSUE THREAD

**Issue by chping2125** [jaywcjlove/store.js#4]
function isJSON(obj) {
        return typeof obj === "object" && Object.prototype.toString.call(obj).toLowerCase() && !obj.length;
 }
这个方法中的 Object.prototype.toString.call(obj).toLowerCase()有什么目的？
这个isJson方法是不是只能判断是不是对象？不能严格判断是不是json格式的对象？

**Comment by jaywcjlove** [comment]
```js
Object.prototype.toString.call(obj).toLowerCase() === "[object object]"
```

漏了

**Comment by jaywcjlove** [comment]
使用`storejs@1.0.13` 版本
