### ISSUE TITLE
Call stack size exceeds when `keys` API is invoked

### ISSUE THREAD

**Issue by saikumarrs** [jaywcjlove/store.js#44]
### Description
When the `keys` API is invoked with at least one entry in local storage with an empty name, the call stack size is exceeded where `forEach` and `get` methods call each other repeatedly.

Screenshot of a Bugsnag issue we've encountered:
```RangeError: Maximum call stack size exceeded```

![image](https://github.com/jaywcjlove/store.js/assets/88789928/2625cef8-a8fd-4255-93f3-34416f1c8d12)

### Steps to reproduce

1. Integrate the `storejs` package into your application.
2. Open your application in the latest Chrome browser.
3. Using DevTools, create, say 2 valid entries in the localstorage.
4. Invoke `storejs.keys().length` through your app's API.
5. This should give us, `2`.
6. Now, delete the name of one of the entries in the localstorage.
7. Invoke `storejs.keys().length`.
8. It'll result in `RangeError: Maximum call stack size exceeded` exception.

**Comment by jaywcjlove** [comment]
![image](https://github.com/jaywcjlove/store.js/assets/1680273/1c7bb59a-7902-4247-9f67-d875014c66bc)

I can't reproduce the issue @saikumarrs

**Comment by jaywcjlove** [comment]
@saikumarrs Upgrade `v2.0.6`
