### ISSUE TITLE
您好，可以写一份 store.d.ts文件吗？

### ISSUE THREAD

**Issue by fxjs** [jaywcjlove/store.js#5]

**Comment by jaywcjlove** [comment]
你可以写一个 `pull requests`

**Comment by fedwatch** [comment]
我这边无法build 报依赖找不到

**Comment by fedwatch** [comment]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:test"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! storejs@1.0.16 build:test: `browserify test/store.js > test/store.test.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the storejs@1.0.16 build:test script 'browserify test/store.js > test/store.test.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the storejs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify test/store.js > test/store.test.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs storejs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls storejs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\zqVue\store.js\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build" "--scripts-prepend-node-path=auto"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! storejs@1.0.16 build: `npm run build:min && npm run build:dist && npm run build:test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the storejs@1.0.16 build script 'npm run build:min && npm run build:dist && npm run build:test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the storejs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:min && npm run build:dist && npm run build:test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs storejs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls storejs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\zqVue\store.js\npm-debug.log

**Comment by jaywcjlove** [comment]
没有Windows系统测试，我的Mac电脑是好的。

可能是文件路径的问题吧。文件路径跟Linux系统是有区别的
